import { v4 as uuidv4 } from 'uuid';

const L = JSON.stringify(['PS', 'DISTRICT', 'HQ']);
const E = JSON.stringify(['PS']);

const MISSING_FIELDS = [
  // ── CASE module ─────────────────────────────────────────────────────────────
  {
    field_key: 'complainant_father_husband_name',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: "Complainant's Father / Husband Name",
    label_hi: 'शिकायतकर्ता के पिता / पति का नाम',
    section: 'complainant_accused_info',
    sort_order: 14,
  },
  {
    field_key: 'accused_name',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Accused Name',
    label_hi: 'अभियुक्त का नाम',
    section: 'complainant_accused_info',
    sort_order: 20,
  },
  {
    field_key: 'accused_father_name',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: "Accused Father's Name",
    label_hi: 'अभियुक्त के पिता का नाम',
    section: 'complainant_accused_info',
    sort_order: 21,
  },
  {
    field_key: 'occurrence_time',
    field_type: 'TIME',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Time of Occurrence',
    label_hi: 'घटना का समय',
    section: 'incident_details',
    sort_order: 8,
  },
  {
    field_key: 'vehicle_no',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Vehicle Registration No.',
    label_hi: 'वाहन पंजीकरण संख्या',
    section: 'vehicle_details',
    sort_order: 50,
    show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft', 'Cycle Theft', 'Robbery', 'Snatching'] }),
  },
  {
    field_key: 'vehicle_type',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Vehicle Type',
    label_hi: 'वाहन का प्रकार',
    section: 'vehicle_details',
    sort_order: 51,
    options: JSON.stringify([
      { value: 'Car', label_en: 'Car', label_hi: 'कार' },
      { value: 'Motorcycle', label_en: 'Motorcycle', label_hi: 'मोटरसाइकिल' },
      { value: 'Scooter', label_en: 'Scooter', label_hi: 'स्कूटर' },
      { value: 'E-Rickshaw', label_en: 'E-Rickshaw', label_hi: 'ई-रिक्शा' },
      { value: 'Auto', label_en: 'Auto Rickshaw', label_hi: 'ऑटो रिक्शा' },
      { value: 'Tempo', label_en: 'Tempo / Truck', label_hi: 'टेम्पो / ट्रक' },
      { value: 'Cycle', label_en: 'Bicycle', label_hi: 'साइकिल' },
      { value: 'Other', label_en: 'Other', label_hi: 'अन्य' },
    ]),
    show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft', 'Cycle Theft', 'Robbery', 'Snatching'] }),
  },
  {
    field_key: 'cd_uploaded_24h',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: '1st CD Uploaded Within 24 Hours',
    label_hi: 'पहली सीडी 24 घंटे में अपलोड की गई',
    section: 'vehicle_details',
    sort_order: 52,
    options: JSON.stringify([
      { value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' },
      { value: 'No', label_en: 'No', label_hi: 'नहीं' },
    ]),
    show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft'] }),
  },
  {
    field_key: 'footage_collected',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'CCTV Footage Collected',
    label_hi: 'सीसीटीवी फुटेज एकत्र किया गया',
    section: 'vehicle_details',
    sort_order: 53,
    options: JSON.stringify([
      { value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' },
      { value: 'No', label_en: 'No', label_hi: 'नहीं' },
    ]),
  },
  {
    field_key: 'rc_no',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'RC No.',
    label_hi: 'आरसी संख्या',
    section: 'investigation_details',
    sort_order: 60,
  },
  {
    field_key: 'disposal_type',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Disposal Type',
    label_hi: 'निपटान प्रकार',
    section: 'investigation_details',
    sort_order: 61,
    options: JSON.stringify([
      { value: 'Challan', label_en: 'Challan', label_hi: 'चालान' },
      { value: 'Untrace', label_en: 'Untraced', label_hi: 'अपता' },
      { value: 'Cancel', label_en: 'Cancelled', label_hi: 'रद्द' },
    ]),
  },
  {
    field_key: 'cause_of_death',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Cause of Death',
    label_hi: 'मृत्यु का कारण',
    section: 'inquest_details',
    sort_order: 70,
    options: JSON.stringify([
      { value: 'Accidental', label_en: 'Accidental', label_hi: 'दुर्घटना' },
      { value: 'Natural', label_en: 'Natural', label_hi: 'प्राकृतिक' },
      { value: 'Suicide', label_en: 'Suicide', label_hi: 'आत्महत्या' },
      { value: 'Murder', label_en: 'Murder', label_hi: 'हत्या' },
      { value: 'Unknown', label_en: 'Unknown', label_hi: 'अज्ञात' },
    ]),
  },
  {
    field_key: 'deceased_father_husband_name',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: "Deceased's Father / Husband Name",
    label_hi: 'मृतक के पिता / पति का नाम',
    section: 'inquest_details',
    sort_order: 71,
  },
  {
    field_key: 'is_important',
    field_type: 'BOOLEAN',
    applicable_record_types: JSON.stringify(['CASE']),
    label_en: 'Mark as Important Case',
    label_hi: 'महत्वपूर्ण मामले के रूप में चिह्नित करें',
    section: 'general_info',
    sort_order: 99,
  },

  // ── ARREST module ────────────────────────────────────────────────────────────
  {
    field_key: 'arrested_father_husband_name',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: "Arrested Person's Father / Husband Name",
    label_hi: 'गिरफ्तार व्यक्ति के पिता / पति का नाम',
    section: 'arrestee_info',
    sort_order: 5,
  },
  {
    field_key: 'age',
    field_type: 'NUMBER',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Age (years)',
    label_hi: 'आयु (वर्ष)',
    section: 'arrestee_info',
    sort_order: 6,
  },
  {
    field_key: 'proclaimed_offender',
    field_type: 'BOOLEAN',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Proclaimed Offender (PO)',
    label_hi: 'घोषित अपराधी (पीओ)',
    section: 'arrest_details',
    sort_order: 21,
  },
  {
    field_key: 'listed_criminal',
    field_type: 'BOOLEAN',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Listed Criminal (BC)',
    label_hi: 'सूचीबद्ध अपराधी (बीसी)',
    section: 'arrest_details',
    sort_order: 22,
  },
  {
    field_key: 'integrated_pi',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via Integrated PI',
    label_hi: 'एकीकृत पीआई से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 30,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'group_patrolling',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via Group Patrolling',
    label_hi: 'समूह गश्त से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 31,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'cycle_patrolling',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via Cycle Patrolling',
    label_hi: 'साइकिल गश्त से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 32,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'by_antisnatching_team',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via Anti-Snatching Team',
    label_hi: 'छीना-झपटी रोधी दल से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 33,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'by_prahari',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via PRAHARI Scheme',
    label_hi: 'प्रहरी योजना से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 34,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'by_eyes_ears_scheme_members',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Arrested via Eyes & Ears Scheme',
    label_hi: 'नेत्र और कान योजना से गिरफ्तार',
    section: 'special_scheme',
    sort_order: 35,
    options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]),
  },
  {
    field_key: 'cheated_amount',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Amount Cheated / Defrauded',
    label_hi: 'धोखाधड़ी की गई राशि',
    section: 'financial_fraud',
    sort_order: 40,
  },
  {
    field_key: 'modus_operandi',
    field_type: 'TEXTAREA',
    applicable_record_types: JSON.stringify(['ARREST']),
    label_en: 'Modus Operandi',
    label_hi: 'अपराध करने का तरीका',
    section: 'financial_fraud',
    sort_order: 41,
  },

  // ── MISSING module ───────────────────────────────────────────────────────────
  {
    field_key: 'missing_address',
    field_type: 'TEXT',
    applicable_record_types: JSON.stringify(['MISSING']),
    label_en: 'Address of Missing Person',
    label_hi: 'लापता व्यक्ति का पता',
    section: 'person_details',
    sort_order: 16,
  },
  {
    field_key: 'source',
    field_type: 'SELECT',
    applicable_record_types: JSON.stringify(['MISSING']),
    label_en: 'Source of Information',
    label_hi: 'सूचना का स्रोत',
    section: 'general_info',
    sort_order: 2,
    options: JSON.stringify([
      { value: 'PCR', label_en: 'PCR Call', label_hi: 'पीसीआर कॉल' },
      { value: 'DD', label_en: 'DD / Written Complaint', label_hi: 'डीडी / लिखित शिकायत' },
    ]),
  },
];

export async function up(knex) {
  for (const f of MISSING_FIELDS) {
    const exists = await knex('field_registry').where({ field_key: f.field_key }).first();
    if (!exists) {
      await knex('field_registry').insert({
        id: uuidv4(),
        is_active: true,
        scope_level: 'global',
        scope_id: null,
        created_by: null,
        section_label_en: null,
        section_label_hi: null,
        validation_rules: JSON.stringify({}),
        visible_to_levels: L,
        editable_by_levels: E,
        ...f,
      });
    }
  }
}

export async function down(knex) {
  const keys = MISSING_FIELDS.map(f => f.field_key);
  await knex('field_registry').whereIn('field_key', keys).delete();
}
